#!/bin/bash -e
echo Deleting local branches that were removed in remotes

git fetch --prune --all
stuff_to_delete=$(git branch -vv | awk '/: gone]/{ print $1 }')

if [[ -z $stuff_to_delete ]]; then
  echo "No local branches to delete."
  exit 0
fi

echo "$stuff_to_delete"  | xargs git branch --delete --force
